export const SEARCH_YOUTUBE = 'SEARCH_YOUTUBE';
export const SEARCH_YOUTUBE_SUCCESS = 'SEARCH_YOUTUBE_SUCCESS';
export const SEARCH_YOUTUBE_FAIL = 'SEARCH_YOUTUBE_FAIL';

export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_ORDER = 'SET_ORDER';
